from database_config.db_settings import execute_query
from database_config.models import create_table


def add_regions_data():
    """
    This function adds regions data to database
    """
    add_regions_data_query = """
    INSERT INTO regions (regions_id, name) VALUES
        (1, 'Andijon viloyati'),
        (2, 'Buxoro viloyati'),
        (3, 'Jizzax viloyati'),
        (4, 'Qashqadaryo viloyati'),
        (5, 'Navoiy viloyati'),
        (6, 'Namangan viloyati'),
        (7, 'Samarqand viloyati'),
        (8, 'Surxondaryo viloyati'),
        (9, 'Sirdaryo viloyati'),
        (10, 'Toshkent shahri'),
        (11, 'Toshkent viloyati'),
        (12, 'Farg`ona viloyati'),
        (13, 'Xorazm viloyati'),
        (14, 'Qoraqalpog`iston Respublikasi');
    """
    execute_query(add_regions_data_query)
    print("Regions added successfully")


def add_districts_data():
    """
    This function adds districts data to database
    """
    add_districts_data_query = """
    INSERT INTO districts (districts_id, regions_id, name) VALUES
        (1, 1, 'Marxamat tumani'),
        (2, 1, 'Andijon tumani'),
        (3, 1, 'Baliqchi tumani'),
        (4, 1, 'Boz tumani'),
        (5, 1, 'Buloqboshi tumani'),
        (6, 1, 'Izboskan tumani'),
        (7, 1, 'Ulugnor tumani'),
        (8, 1, 'Qorgontepa tumani'),
        (9, 1, 'Asaka tumani'),
        (10, 1, 'Paxtaobod tumani'),
        (11, 1, 'Jalolquduq tumani'),
        (12, 1, 'Oltinkol tumani'),
        (13, 1, 'Xojaobod tumani'),
        (14, 1, 'Shahrixon tumani'),
        (15, 1, 'Andijon shahri'),
        (16, 1, 'Xonobod shahri'),
        (17, 2, 'Olot tumani'),
        (18, 2, 'Buxoro tumani'),
        (19, 2, 'Vobkent tumani'),
        (20, 2, 'Kogon tumani'),
        (21, 2, 'Qorakol tumani'),
        (22, 2, 'Qorovulbozor tumani'),
        (23, 2, 'Peshku tumani'),
        (24, 2, 'Romitan tumani'),
        (25, 2, 'Shofirkon tumani'),
        (26, 2, 'Jondor tumani'),
        (27, 2, 'Buxoro shahri'),
        (28, 2, 'Kogon shahri'),
        (29, 2, 'Gijduvon tumani'),
        (30, 3, 'Dostlik tumani'),
        (31, 3, 'Zomin tumani'),
        (32, 3, 'Zarbdor tumani'),
        (33, 3, 'Mirzachol tumani'),
        (34, 3, 'Forish tumani'),
        (35, 3, 'Arnasoy tumani'),
        (36, 3, 'Baxmal tumani'),
        (37, 3, 'Gallaorol tumani'),
        (38, 3, 'Yangiobod tumani'),
        (39, 3, 'Jizzax shahri'),
        (40, 3, 'Paxtakor tumani'),
        (41, 3, 'Zafarobod tumani'),
        (42, 3, 'Sharof Rashidov tumani'),
        (43, 4, 'Muborak tumani'),
        (44, 4, 'Kasbi tumani'),
        (45, 4, 'Guzor tumani'),
        (46, 4, 'Dehqonobod tumani'),
        (47, 4, 'Qamashi tumani'),
        (48, 4, 'Qarshi shahri'),
        (49, 4, 'Chiroqchi tumani'),
        (50, 4, 'Shahrisabz tumani'),
        (51, 4, 'Yakkabog tumani'),
        (52, 4, 'Qarshi tumani'),
        (53, 4, 'Koson tumani'),
        (54, 4, 'Kitob tumani'),
        (55, 4, 'Mirishkor tumani'),
        (56, 4, 'Nishon tumani'),
        (57, 4, 'Shahrisabz shahri'),
        (58, 5, 'Konimex tumani'),
        (59, 5, 'Qiziltepa tumani'),
        (60, 5, 'Navbahor tumani'),
        (61, 5, 'Karmana tumani'),
        (62, 5, 'Nurota tumani'),
        (63, 5, 'Uchquduq tumani'),
        (64, 5, 'Xatirchi tumani'),
        (65, 5, 'Navoiy shahri'),
        (66, 5, 'Tomdi tumani'),
        (67, 5, 'Zarafshon shahri'),
        (68, 6, 'Mingbuloq tumani'),
        (69, 6, 'Kosonsoy tumani'),
        (70, 6, 'Namangan tumani'),
        (71, 6, 'Norin tumani'),
        (72, 6, 'Pop tumani'),
        (73, 6, 'Toraqorgon tumani'),
        (74, 6, 'Uychi tumani'),
        (75, 6, 'Uchqorgon tumani'),
        (76, 6, 'Chortoq tumani'),
        (77, 6, 'Chust tumani'),
        (78, 6, 'Namangan shahri'),
        (79, 6, 'Yangiqorgon tumani'),
        (80, 7, 'Qoshrabot tumani'),
        (81, 7, 'Samarqand shahri'),
        (82, 7, 'Ishtixon tumani'),
        (83, 7, 'Kattaqorgon tumani'),
        (84, 7, 'Oqdaryo tumani'),
        (85, 7, 'Bulungur tumani'),
        (86, 7, 'Jomboy tumani'),
        (87, 7, 'Narpay tumani'),
        (88, 7, 'Pastdargom tumani'),
        (89, 7, 'Paxtachi tumani'),
        (90, 7, 'Samarqand tumani'),
        (91, 7, 'Nurobod tumani'),
        (92, 7, 'Urgut tumani'),
        (93, 7, 'Tayloq tumani'),
        (94, 7, 'Payariq tumani'),
        (95, 7, 'Kattaqorgon shahri'),
        (96, 8, 'Oltinsoy tumani'),
        (97, 8, 'Angor tumani'),
        (98, 8, 'Boysun tumani'),
        (99, 8, 'Denov tumani'),
        (100, 8, 'Qumqorgon tumani'),
        (101, 8, 'Qiziriq tumani'),
        (102, 8, 'Sariosiyo tumani'),
        (103, 8, 'Termiz tumani'),
        (104, 8, 'Uzun tumani'),
        (105, 8, 'Sherobod tumani'),
        (106, 8, 'Shorchi tumani'),
        (107, 8, 'Termiz shahri'),
        (108, 8, 'Muzrabot tumani'),
        (109, 8, 'Jarqorgon tumani'),
        (110, 9, 'Mirzaobod tumani'),
        (111, 9, 'Sirdaryo tumani'),
        (112, 9, 'Oqoltin tumani'),
        (113, 9, 'Boyovut tumani'),
        (114, 9, 'Guliston tumani'),
        (115, 9, 'Sayxunobod tumani'),
        (116, 9, 'Sardoba tumani'),
        (117, 9, 'Shirin shahri'),
        (118, 9, 'Yangiyer shahri'),
        (119, 9, 'Xovos tumani'),
        (120, 9, 'Guliston shahri'),
        (121, 10, 'Yunusobod tumani'),
        (122, 10, 'Uchtepa tumani'),
        (123, 10, 'Bektemir tumani'),
        (124, 10, 'Mirzo Ulugbek tumani'),
        (125, 10, 'Mirobod tumani'),
        (126, 10, 'Olmazor tumani'),
        (127, 10, 'Sirgali tumani'),
        (128, 10, 'Yakkasaroy tumani'),
        (129, 10, 'Chilonzor tumani'),
        (130, 10, 'Yashnobod tumani'),
        (131, 10, 'Shayxontohur tumani'),
        (132, 11, 'Boka tumani'),
        (133, 11, 'Oqqorgon tumani'),
        (134, 11, 'Ohangaron tumani'),
        (135, 11, 'Bekobod tumani'),
        (136, 11, 'Bostonliq tumani'),
        (137, 11, 'Zangiota tumani'),
        (138, 11, 'Qibray tumani'),
        (139, 11, 'Parkent tumani'),
        (140, 11, 'Ortachirchiq tumani'),
        (141, 11, 'Chinoz tumani'),
        (142, 11, 'Yangiyol tumani'),
        (143, 11, 'Yuqorichirchiq tumani'),
        (144, 11, 'Pskent tumani'),
        (145, 11, 'Olmaliq shahri'),
        (146, 11, 'Angren shahri'),
        (147, 11, 'Chirchiq shahri'),
        (148, 11, 'Quyichirchiq tumani'),
        (149, 11, 'Toshkent tumani'),
        (150, 11, 'Nurafshon shahri'),
        (151, 11, 'Bekobod shahri'),
        (152, 11, 'Ohangaron shahri'),
        (153, 11, 'Yangiyol shahri'),
        (154, 12, 'Quva tumani'),
        (155, 12, 'Dangara tumani'),
        (156, 12, 'Sox tumani'),
        (157, 12, 'Oltiariq tumani'),
        (158, 12, 'Qoshtepa tumani'),
        (159, 12, 'Bogdod tumani'),
        (160, 12, 'Buvayda tumani'),
        (161, 12, 'Beshariq tumani'),
        (162, 12, 'Uchkoprik tumani'),
        (163, 12, 'Rishton tumani'),
        (164, 12, 'Toshloq tumani'),
        (165, 12, 'Ozbekiston tumani'),
        (166, 12, 'Fargona tumani'),
        (167, 12, 'Furqat tumani'),
        (168, 12, 'Yozyovon tumani'),
        (169, 12, 'Fargona shahri'),
        (170, 12, 'Qoqon shahri'),
        (171, 12, 'Quvasoy shahri'),
        (172, 12, 'Margilon shahri'),
        (173, 13, 'Hazorasp tumani'),
        (174, 13, 'Yangiariq tumani'),
        (175, 13, 'Yangibozor tumani'),
        (176, 13, 'Xonqa tumani'),
        (177, 13, 'Xiva tumani'),
        (178, 13, 'Urganch shahri'),
        (179, 13, 'Shovot tumani'),
        (180, 13, 'Bogot tumani'),
        (181, 13, 'Gurlan tumani'),
        (182, 13, 'Qoshkopir tumani'),
        (183, 13, 'Urganch tumani'),
        (184, 13, 'Xiva shahri'),
        (185, 14, 'Beruniy tumani'),
        (186, 14, 'Qoraozak tumani'),
        (187, 14, 'Kegeyli tumani'),
        (188, 14, 'Qongirot tumani'),
        (189, 14, 'Qanlikol tumani'),
        (190, 14, 'Moynoq tumani'),
        (191, 14, 'Shumanay tumani'),
        (192, 14, 'Ellikkala tumani'),
        (193, 14, 'Nukus shahri'),
        (194, 14, 'Amudaryo tumani'),
        (195, 14, 'Nukus tumani'),
        (196, 14, 'Taxtakopir tumani'),
        (197, 14, 'Tortkol tumani'),
        (198, 14, 'Xojayli tumani'),
        (199, 14, 'Chimboy tumani'),
        (200, 14, 'Taxiatosh tumani');  
        """

    execute_query(add_districts_data_query)
    print("Regions added successfully")


def add_status_data():
    add_status_data_query = """
    INSERT INTO statuses (status_name) VALUES 
    ('pending'), 
    ('accepted'), 
    ('rejected');
    """
    execute_query(add_status_data_query)
    print("Status data added successfully")
